config/routes.rb
Rails.application.routes.draw do
  resources :boxes do
    collection do
      get :list_ajax
      get :list
    end
  end

  post 'folders/create' => 'folders#create'

  root 'boxes#index'

end

app/models/box.rb
class Box < ActiveRecord::Base
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  before_action :build_gon

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.where(node_id: params[:node_id] || Folder.first.id)
  end

  def list
    @boxes = Box.where(node_id: params[:node_id])
    if request.headers['X-PJAX']
      render :layout => false
    else
      redirect_to action: :index, node_id: params[:node_id]
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new(node_id: params[:node_id])
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def build_gon
    gon.tree = Folder.all.arrange_serializable
    gon.current_node = params[:node_id] || 1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :node_id)
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  def create
    parent = Folder.find_by_id(params[:node_id])
    Folder.create(label: params[:folder_label], parent: parent)
    render :json => Folder.all.arrange_serializable
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.hidden_field :node_id %>    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.title %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boxes</h1>
<div class="row" id="tree_vue">
  <div class="col-sm-4">
    <div id="tree"></div>
    <%= text_field_tag "new_folder_label", "", "v-model": "newFolderLabel" %>
    <%= button_tag "追加", "v-on:click": "addFolder" %>
  </div>

  <div class="col-sm-8">
    <div id="data_ajax">
      <%= render partial: 'list' %>
    </div>

    <br>
    <a v-on:click="createBox" v-bind:style="styleObject">New Box</a>
  </div>
</div>

app/views/boxes/list.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.title %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boxes/list_ajax.js.erb
$("#data_ajax").html("<%= escape_javascript(render partial: "list") %>");

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @box.title %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cabinet</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>